### post a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name":"broke lesnar",
    "email":"broke_22@example.com",
    "address":"wowthis my updated address",
    "dateOfBirth":"2004-03-21"
    
}